import { auth } from '@/auth';
import './globals.css';
import Footer from "@/components/Footer";
import Navbar from '@/components/dashboard/Navbar';
import Sidebar from "@/components/dashboard/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    
    if (!session) return null;

    const { user:currentUser } = session;

    return (
        <main className="w-full bg-[rgba(252,252,252,1)]">
            <Navbar currentUser={currentUser} />
            <div className="flex gap-[48px] pt-[42px] px-[32px]">
                <Sidebar currentUser={currentUser} />
                {children}
            </div>
            <div className="mt-[32px]" />
            <Footer />
        </main>
    );
}
