import './globals.css';
import Footer from "@/components/Footer";
import Sidebar from "@/components/dashboard/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="w-full bg-[rgba(252,252,252,1)]">
            <div className="flex gap-[48px] pt-[42px] px-[32px]">
                <Sidebar/>
                {children}
            </div>
            <div className="mt-[32px]" />
            <Footer />
        </main>
    );
}
